version: '3.8'

volumes:
  next-data:
    name: "next-data"
  next-db:
    name: "next-db"

networks:
  next-intern:
    name: "next-intern"
  frontend:
    name: "frontend"

services:
  next-db:
    image: mariadb:10.5
    build: db
    container_name: next-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - next-db:/var/lib/mysql
    env_file:
      - .mariadb.env
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - setgid
      - setuid

    networks:
      - next-intern
    
  next-app:
    image: nextcloud:20.0.7-apache
    build: app
    container_name: next-app
    volumes:
      - next-data:/var/www/html
   # environment:
   #   - APACHE_DISABLE_REWRITE_IP=1
   #   - OVERWRITEHOST=nginx-proxy
   #   - OVERWRITEPROTOCOL=https
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - chown
      - setgid
      - setuid
    networks:
      - next-intern
      - frontend
