version: '3.8'

volumes:
  letsencrypt:
    name: "letsencrypt"
  www:
    name: "www"

networks:
  frontend:
    name: "frontend"

services:
  nginx-proxy:
    image: nginx:1.19
    build: nginx-proxy
    container_name: nginx-proxy
    restart: always
    env_file:
      - nginx-proxy/nginx.env
    volumes:
      - letsencrypt:/etc/letsencrypt/ 
      - www:/var/www/html
    ports:
      - 80:80
      - 443:443
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - chown
      - setgid
      - setuid
      - net_bind_service
    networks:
      - frontend
