version: '3.8'

volumes:
  nextcloud:
  db:

networks:
  next-intern:
    name: "next-intern"

services:
  db:
    image: mariadb:10.5
    build: db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    cap_drop:
      - ALL
    cap_add:
      - dac_read_search
      - setgid
      - setuid

    networks:
      - next-intern
    
  app:
    image: nextcloud
    build: app
    ports:
      - 8080:8080
    volumes:
      - nextcloud:/var/www/html
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - setgid
      - setuid
    networks:
      - next-intern
