version: '3.8'

volumes:
  next-data:
    name: "next-data"
  next-db:
    name: "next-db"

networks:
  next-intern:
    name: "next-intern"
  frontend:
    name: "frontend"

services:
  db:
    image: mariadb:10.5
    build: db
    container_name: next-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - next-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - setgid
      - setuid

    networks:
      - next-intern
    
  app:
    image: nextcloud
    build: app
    container_name: next-app
    volumes:
      - next-data:/var/www/html
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - chown
      - setgid
      - setuid
    networks:
      - next-intern
      - frontend
